export const defaultTopics = [
    'destinations',
    'boarding',
    'seating',
    'baggage',
    'cargo',
    'check-in',
    'covid-19',
    'boarding passes',
    'flight status',
    'delays',
    'food',
    'beverages',
    'in-flight entertainment',
    'in-flight services',
    'in-flight shopping',
    'lounge access',
    'luggage',
    'lost items',
    'medical assistance',
    'pet travel',
    'pets',
    'special assistance',
    'documents',
    'insurance',
    'children',
    'sports equipment',
    'special needs',
    'valuables',
    'weapons',
    'wheelchairs',
    'disabilities',
    'infants',
    'extra luggage',
    'safety',
    'lounge',
    'restrictions',
    'luggage restrictions',
    'payment methods'
]
